volumes:
  keycloak-postgres:
    external: false

services:
  keycloak:
    build:
        context: .
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_SCHEMA=public
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_HOST=keycloak-postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
    command:
      - start-dev
    depends_on:
      - keycloak-postgres
    ports:
      - '8080:8080'

  keycloak-postgres:
    image: postgres:17-alpine
    container_name: keycloak-postgres
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
        POSTGRES_DB: keycloak
    ports:
      - '5432:5432'